attributes:
  metadata:
    group: 'storage'
  default_backend:
    value: false
    label: 'MOS Backend Enabled'
    description: 'If the option is checked, MOS default backend (LVM over iSCSI\Ceph) will be used along with NetApp'
    weight: 10
    type: 'checkbox'

# Storage Type
  netapp_storage_family:
    value: 'ontap_cluster'
    values:
        - data: 'ontap_cluster'
          label: 'Clustered Data ONTAP'
          description: ''
        - data: 'ontap_7mode'
          label: 'Data ONTAP 7-Mode'
          description: ''
        - data: 'eseries'
          label: 'E-Series/EF-Series'
          description: ''
    label: 'NetApp Storage Family'
    weight: 11
    type: 'radio'
  netapp_storage_protocol:
    value: 'iscsi'
    values:
        - data: 'iscsi'
          label: 'iSCSI'
          description: ''
        - data: 'nfs'
          label: 'NFS'
          description: ''
          restrictions:
            - condition: "settings:cinder_netapp.netapp_storage_family.value == 'eseries'"
              action: 'hide'
    label: 'NetApp Storage Protocol'
    description: 'The storage protocol to be used on the data path with the storage system'
    weight: 12
    type: 'radio'

# Authorisation
  netapp_login:
    value: ''
    label: 'Username'
    description: 'Administrative user account name used to access the storage system or proxy server'
    weight: 21
    type: 'text'
  netapp_password:
    value: ''
    label: 'Password'
    description: 'Password for the administrative user account'
    weight: 22
    type: 'password'

# Connection
  netapp_server_hostname:
    value: ''
    label: 'NetApp Storage Hostname/IP'
    description: 'The hostname or IP address for the storage system or proxy server'
    weight: 31
    type: 'text'
  netapp_server_port:
    value: ''
    label: 'NetApp Storage Port'
    description: 'The TCP port to use for communication with the storage system or proxy server. If not specified, Data ONTAP drivers will use 80 for HTTP and 443 for HTTPS; E-Series will use 8080 for HTTP and 8443 for HTTPS'
    weight: 32
    type: 'text'
  netapp_transport_type:
    value: 'http'
    values:
        - data: 'http'
          label: 'http'
          description: ''
        - data: 'https'
          label: 'https'
          description: ''
    label: 'Transport Type'
    description: 'The transport protocol used for communication with the storage system or proxy server'
    weight: 33
    type: 'radio'

# NFS Shares
  nfs_server_ip:
    value: ''
    label: 'CDOT Data LIF IP address'
    description: 'The Data LIF IP address is part of the NFS export location (e.g. If the export is 10.10.10.10:/cinder_flexvol, this value will be 10.10.10.10)'
    weight: 41
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'
  nb_share:
    type: 'select'
    weight: 42
    value: '1'
    label: 'NFS shares'
    description: 'Number of Netapp NFS shares'
    values:
      - data: '1'
        label: '1'
      - data: '2'
        label: '2'
      - data: '3'
        label: '3'
      - data: '4'
        label: '4'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'
  nfs_server_share1:
    value: ''
    label: 'CDOT FlexVol volume junction path'
    description: 'The junction path is part of the NFS export location and specifies the path for the FlexVol volume in which Cinder volumes should be placed (e.g. If the export is 10.10.10.10:/cinder_flexvol, this value will be /cinder_flexvol)'
    weight: 43
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'
  nfs_server_share2:
    value: ''
    label: 'CDOT FlexVol volume junction path 2'
    description: 'The junction path is part of the NFS export location and specifies the path for the FlexVol volume in which Cinder volumes should be placed (e.g. If the export is 10.10.10.10:/cinder_flexvol_2, this value will be /cinder_flexvol_2)'
    weight: 44
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs' or settings:cinder_netapp.nb_share.value != '2' and settings:cinder_netapp.nb_share.value != '3' and settings:cinder_netapp.nb_share.value != '4'"
        action: 'hide'
  nfs_server_share3:
    value: ''
    label: 'CDOT FlexVol volume junction path 3'
    description: 'The junction path is part of the NFS export location and specifies the path for the FlexVol volume in which Cinder volumes should be placed (e.g. If the export is 10.10.10.10:/cinder_flexvol_3, this value will be /cinder_flexvol_3)'
    weight: 45
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs' or settings:cinder_netapp.nb_share.value != '3' and settings:cinder_netapp.nb_share.value != '4'"
        action: "hide"
  nfs_server_share4:
    value: ''
    label: 'CDOT FlexVol volume junction path 4'
    description: 'The junction path is part of the NFS export location and specifies the path for the FlexVol volume in which Cinder volumes should be placed (e.g. If the export is 10.10.10.10:/cinder_flexvol_4, this value will be /cinder_flexvol_4)'
    weight: 46
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs' or settings:cinder_netapp.nb_share.value != '4'"
        action: 'hide'

# Ontap Cluster
  netapp_vserver:
    value: ''
    label: 'Storage Virtual Machine'
    description: 'This option specifies the storage virtual machine (vserver) name in which provisioning of block storage volumes should occur'
    weight: 51
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'ontap_cluster'"
        action: 'hide'

# 7-Mode
  netapp_vfiler:
    value: ''
    label: 'vFiler'
    description: '(Optional) The vFiler unit on which provisioning of block storage volumes will be done'
    weight: 51
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'ontap_7mode'"
        action: 'hide'

# E-Series
  netapp_controller_ips:
    value: ''
    label: 'Controller IPs'
    description: 'This option is used to restrict provisioning to the specified controllers. Specify the value of this option to be a comma separated list of controller management hostnames or IP addresses to be used for provisioning'
    weight: 51
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'eseries'"
        action: 'hide'
  netapp_sa_password:
    value: ''
    label: 'Storage Array Password'
    description: 'Password for the NetApp E-Series storage array'
    weight: 52
    type: 'password'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'eseries'"
        action: 'hide'
  netapp_eseries_host_type:
    value: 'linux_dm_mp'
    label: 'Host Type'
    description: '(Optional) This option defines the type of operating system for all initiators that can access a LUN'
    weight: 62
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'eseries'"
        action: 'hide'
  netapp_enable_multiattach:
    value: false
    label: 'Multiattach'
    description: '(Optional) This option specifies whether the driver should allow operations that require multiple attachments to a volume'
    weight: 63
    type: 'checkbox'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_family.value != 'eseries'"
        action: "hide"

# NFS Options
  nfs_mount_options:
    value: ''
    label: 'NFS Mount Options'
    description: '(Optional) This option will be used when mounting shares on the Storage and Compute nodes'
    weight: 61
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'
  thres_avl_size_perc_start:
    value: '20'
    label: 'Threshold Available Size (% Start)'
    description: '(Optional) If the percentage of available space for an NFS share has dropped below the value specified by this option, the NFS image cache will be cleaned'
    weight: 62
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: "hide"
  thres_avl_size_perc_stop:
    value: '60'
    label: 'Threshold Available Size (% Stop)'
    description: '(Optional) When the percentage of available space on an NFS share has reached the percentage specified by this option, the driver will stop clearing files from the NFS image cache'
    weight: 63
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'
  expiry_thres_minutes:
    value: '720'
    label: 'Expiry Threshold (Minutes)'
    description: '(Optional) This option specifies the threshold for last access time for images in the NFS image cache'
    weight: 64
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs'"
        action: 'hide'

# Ontap Cluster with NFS
  netapp_copyoffload_tool_path:
    value: ''
    label: 'Copy Offload Tool Path'
    description: '(Optional) This option specifies the path of the NetApp copy offload tool binary'
    weight: 65
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'nfs' or settings:cinder_netapp.netapp_storage_family.value != 'ontap_cluster'"
        action: 'hide'

# iSCSI
  netapp_pool_name_search_pattern:
    value: '(.+)'
    label: 'Pool Search Pattern'
    description: '(Optional) This option is used to restrict provisioning to the specified volume groups or disk pools. Specify the value of this option as a regular expression which will be applied to the names of volume groups or disk pools from the storage backend which represent pools in Cinder'
    weight: 61
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'iscsi'"
        action: "hide"
  use_multipath_for_image_xfer:
    value: true
    label: 'Multipath for Image Transfer'
    description: '(Optional) If multipath has been enabled on your OpenStack hosts, then setting this option will permit Cinder to use multiple paths for increased bandwidth'
    weight: 65
    type: 'checkbox'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'iscsi'"
        action: 'hide'

# iSCSI with ONTAP
  netapp_host_type:
    value: 'linux'
    label: 'Host Type'
    description: '(Optional) This option defines the type of operating system for all initiators that can access a LUN'
    weight: 62
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'iscsi' or settings:cinder_netapp.netapp_storage_family.value == 'eseries'"
        action: "hide"
  netapp_lun_ostype:
    value: 'linux'
    label: 'LUN OS type'
    description: '(Optional) This option defines the type of operating system that will access a LUN exported from Data ONTAP'
    weight: 63
    type: 'text'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'iscsi' or settings:cinder_netapp.netapp_storage_family.value == 'eseries'"
        action: 'hide'
  netapp_lun_space_reservation:
    value: true
    label: 'LUN Space Reservation'
    description: '(Optional) This option specifies whether space will be reserved when creating Cinder volumes on NetApp backends using the iSCSI protocol'
    weight: 64
    type: 'checkbox'
    restrictions:
      - condition: "settings:cinder_netapp.netapp_storage_protocol.value != 'iscsi' or settings:cinder_netapp.netapp_storage_family.value == 'eseries'"
        action: 'hide'

# Common
  reserved_percentage:
    value: '0'
    label: 'Reserved Percentage'
    description: '(Optional) This option represents the amount of total capacity of a storage pool that will be reserved and cannot be utilized for provisioning Cinder volumes'
    weight: 71
    type: 'text'
  max_oversubscription_ratio:
    value: '1.0'
    label: 'Oversubscription Ratio'
    description: '(Optional) This option specifies the amount of over-provisioning to allow when thin provisioning is used in the storage pool. A value of 1.0 will mean that the provisioned capacity will not be able to exceed the total capacity, while larger values will result in increased levels of over-provisioning'
    weight: 72
    type: 'text'
